[package]
name = "actix_api_response"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
actix-web = "4"
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.91"
